#@package _global_
mephisto:
  blueprint:
    custom_source_dir: ${task_dir}/webapp
    onboarding_qualification: test-parlai-chat-qualification
  task:
    task_name: parlai-chat-example
    task_title: "Negotiate a deal with a partner! Earn upto $5 instantly for one HIT."
    task_description: >
      Please use an updated browser for this HIT. You will first be given a quick tutorial on how to negotiate. Then, you will negotiate with a partner using alternating chat messages to arrive at an agreement. You will earn $0.05 base pay (after completing first stage and being matched with a partner) and $1.95 on completion (when none of the partners disconnects mid-way). Additionally, you can earn up to $3 in bonus, depending on performance and quality. The task is about 20 minutes.
    task_reward: 0.3
    task_tags: "dynamic,chat,dialog,text,emotion,negotiation,conversation,survey,assistant,education,fun"